name: stock_tracker
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.5.1
  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  http: ^1.2.2
  fl_chart: ^0.68.0
  intl: ^0.17.0
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true

  assets:
     - .env

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

